-- Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com). All Rights Reserved.
--
-- This software is the property of WSO2 LLC. and its suppliers, if any.
-- Dissemination of any information or reproduction of any material contained
-- herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
-- You may not alter or remove any copyright or other notice from copies of this content.

-- One-time backfill of outage_communication, for the DEV instance ONLY.
--
-- *** THIS IS NOT A MIGRATION AND MUST NOT BECOME ONE. *** The rows below are
-- dev content -- lorem ipsum, localhost links, one author. Running them
-- against production would insert dev text onto the public status page.
--
-- Produced by discovery PASS 17 in
--   integrations/csm-flow-service/docs/servicenow-discovery/
--     44-outage-cloud-status-flows.js
-- which reads sys_journal_field for element u_external_outage_communications
-- and emits these statements. Run that pass against whichever ServiceNow
-- instance a given environment is migrating from, and apply ITS output there.
--
-- Why a table rather than the existing outage.external_outage_communications
-- column: PASS 17 measured 17 entries across 7 outages, 4 of which carry
-- more than one and one of which carries five. A single column cannot hold
-- a list, and the endpoint publishes them newest-first with timestamps.
-- *** ONE TRANSACTION, BECAUSE THE FIRST STATEMENT IS A DELETE. *** Every
-- INSERT below references an outage through a foreign key. Without a
-- transaction, one missing outage fails its INSERT after the DELETE has
-- already committed, leaving the table empty or half filled -- and the
-- migration's own comment calls this table first-class data after cutover.
-- Run against the wrong database and an unwrapped script wipes real
-- customer-facing updates with no way back.
BEGIN;

DELETE FROM outage_communication;

-- *** ONE LINE PER STATEMENT, WITH \r AND \n ESCAPED (Postgres E'' strings).
-- *** The journal values are HTML with CRLF line endings. An earlier version
-- of this file wrote them as raw multi-line literals, and copying those
-- through a terminal silently dropped every carriage return -- which was
-- measured: the backfill differed from the live API on exactly three
-- outages, and the whole delta was missing \r. Keep each statement on one
-- line so the whitespace survives transit.
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'26a2917a-1bc5-b210-0bb3-da47b04bcb0f'::uuid, E'[code]<p><strong>Investigating</strong></p>\r\n<p><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</span></p>[/code]', E'2025-11-10 05:09:38'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'606f5cc0-1b9b-72d0-0bb3-da47b04bcbbc'::uuid, E'[code]<p>Mitigations were applied by the Engineering Team to the respective feature.</p>[/code]', E'2026-05-11 06:52:59'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'606f5cc0-1b9b-72d0-0bb3-da47b04bcbbc'::uuid, E'[code]<p>The incident was discovered by the Engineering team responsible for this feature.</p>[/code]', E'2026-05-11 06:51:49'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'6597f046-1b91-3610-a002-c9d3604bcbf8'::uuid, E'[code]<p>New Outage</p>[/code]', E'2025-11-20 05:30:34'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'79adad2d-1b45-fa10-0bb3-da47b04bcb46'::uuid, E'[code]<p><strong>Update</strong></p>\r\n<p><strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255);">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span></p>\r\n<p><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;"><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</span></span></p>[/code]', E'2025-11-07 02:36:44'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'79adad2d-1b45-fa10-0bb3-da47b04bcb46'::uuid, E'[code]<p><span style="font-family: verdana, geneva;"><strong>Resolved</strong></span></p>\r\n<p><span style="font-family: verdana, geneva;">The incident has been mitigated by applying hot-fixes to the necessary components.</span></p>\r\n<p><span style="font-family: verdana, geneva;">More details can be found in <a title="Asgardeo Status Page" href="http://localhost:3000/history" target="_blank" rel="noopener">here</a>.</span></p>[/code]', E'2025-11-07 02:29:51'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'79adad2d-1b45-fa10-0bb3-da47b04bcb46'::uuid, E'[code]<p style="box-sizing: border-box; margin-top: 0px; color: rgb(21, 25, 32); font-family: Lato, Arial, sans-serif; font-size: 16px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="font-family: \'times new roman\', times;"><strong style="box-sizing: border-box;">Update</strong></span></p>\r\n<p style="box-sizing: border-box; color: rgb(21, 25, 32); font-family: Lato, Arial, sans-serif; font-size: 16px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="font-family: \'times new roman\', times;">This is to provide an update on the ongoing service disruption.</span></p>\r\n<p style="box-sizing: border-box; margin-bottom: 0px; color: rgb(21, 25, 32); font-family: Lato, Arial, sans-serif; font-size: 16px; white-space: normal; background-color: rgb(255, 255, 255);"><span style="font-family: \'times new roman\', times;">We\'ll provide an update soon.</span></p>[/code]', E'2025-11-07 02:25:22'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'79adad2d-1b45-fa10-0bb3-da47b04bcb46'::uuid, E'[code]<p>This another comment from the Outage itself. Providing an update about the outage and its status. This update message contains spaces,&nbsp;</p>\r\n<p>Newlines</p>\r\n<p><strong>Bold,&nbsp;</strong><em>Italic,&nbsp;</em>and <span style="text-decoration: underline;">underline.</span> Also, this contains the following points</p>\r\n<ol>\r\n<li>One</li>\r\n<li>Two</li>\r\n</ol>\r\n<p>Also, some bullet points</p>\r\n<ul>\r\n<li>One</li>\r\n<li>Two</li>\r\n<li>Three</li>\r\n</ul>\r\n<p>This to check the rendering at the Frontend when using the HTML inputs for the Journals.</p>\r\n<p>Thanks</p>[/code]', E'2025-11-06 10:18:04'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'79adad2d-1b45-fa10-0bb3-da47b04bcb46'::uuid, E'[code]<p>This is an external comment added in Outage: OUT0001856</p>[/code]', E'2025-11-06 09:54:40'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'941d71be-1b0d-b210-0bb3-da47b04bcb14'::uuid, E'[code]<p><a title="Azure Status Title" href="https://azure.status.microsoft/en-gb/status">Azure Status</a></p>[/code]', E'2025-11-10 08:29:59'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'941d71be-1b0d-b210-0bb3-da47b04bcb14'::uuid, E'[code]<p><strong>Update</strong></p>\r\n<p><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</span></p>\r\n<p><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;"><a title="Azure Status" href="https://azure.status.microsoft/en-gb/status">https://azure.status.microsoft/en-gb/status</a></span></p>[/code]', E'2025-11-10 08:29:10'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'941d71be-1b0d-b210-0bb3-da47b04bcb14'::uuid, E'[code]<p><strong>Update&nbsp;</strong></p>\r\n<p><strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255);">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type <em>specimen book</em>. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the <span style="text-decoration: underline;">release of Letraset </span>sheets containing Lorem Ipsum passages, and more recently with desktop publishing </span></p>\r\n<ol>\r\n<li style="font-size: 14px;"><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">Here you go&nbsp;</span></li>\r\n</ol>\r\n<p><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">software like Aldus PageMaker including versions of Lorem Ipsum.</span></p>[/code]', E'2025-11-10 08:26:01'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'941d71be-1b0d-b210-0bb3-da47b04bcb14'::uuid, E'[code]<p><strong><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">Investigating</span></strong></p>\r\n<p><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</span></p>[/code]', E'2025-11-10 08:19:21'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'b8ff285f-1b41-b610-0bb3-da47b04bcbe2'::uuid, E'[code]<p>This is another external communication</p>[/code]', E'2025-11-20 05:26:38'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'b8ff285f-1b41-b610-0bb3-da47b04bcbe2'::uuid, E'[code]<p>Another External Communications</p>[/code]', E'2025-11-20 05:21:06'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'b8ff285f-1b41-b610-0bb3-da47b04bcbe2'::uuid, E'[code]<p>This is an external communication</p>[/code]', E'2025-11-20 05:15:08'::timestamptz, E'athiththan@wso2.com');
INSERT INTO outage_communication (outage_id, comment, created_on, created_by) VALUES (E'f2805136-1bc5-b210-0bb3-da47b04bcb23'::uuid, E'[code]<p><strong>Investigating</strong></p>\r\n<p><span style="color: rgb(0, 0, 0); font-family: \'Open Sans\', Arial, sans-serif; font-size: 14px; text-align: justify; white-space: normal; background-color: rgb(255, 255, 255); float: none; display: inline;">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</span></p>[/code]', E'2025-11-10 05:04:14'::timestamptz, E'athiththan@wso2.com');

COMMIT;
