# Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Local-dev image for this service. Choreo deploys it from source via its
# own buildpack in every other environment -- this Dockerfile exists only
# so the service can run in the docker-compose stack described in
# apps/csm-portal/README.md.

FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /out/csm-portal-backend ./cmd/server

FROM alpine:3.20

# ca-certificates: this service (or one it talks to over TLS, e.g. a Kafka
# SASL_SSL broker or an HTTPS upstream) needs a real trust store, not just
# Go's built-in one, to verify the local dev CA generated by
# scripts/csm-compose/gen-dev-certs.sh.
RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /out/csm-portal-backend ./csm-portal-backend
# Default DASHBOARDS_DIR (see .env.example) -- required at startup, not
# just a fixture, so it has to ship in the image, not only the builder
# stage's source checkout.
COPY dashboards.example ./dashboards.example

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid 10102 \
    "csmdev" \
  && chown -R csmdev:csmdev ./dashboards.example

USER 10102

ENTRYPOINT ["./csm-portal-backend"]
