-- Human-readable, ServiceNow-style sequential alert numbers (ALT0000001,
-- ALT0000002, ...), generated by this service's own dedicated Postgres --
-- never CSM's database. Becomes the externally-facing identifier for a
-- buffered alert: the dedup tag embedded in CreateIncidentRequest.Subject
-- (see internal/csmclient.DedupTag), the id returned from POST /alerts'
-- 202 response, and what gets logged as "the" alert reference. alert_buffer's
-- existing `id` UUID stays the DB primary key -- it is still what every
-- UPDATE/WHERE in internal/store/postgres.go keys off -- this column is
-- purely an additional, externally-facing label.
CREATE SEQUENCE IF NOT EXISTS alert_number_seq START 1;

ALTER TABLE alert_buffer
  ADD COLUMN IF NOT EXISTS alert_number TEXT;

-- Backfill any pre-existing rows so the NOT NULL/UNIQUE constraints below
-- can be applied. In practice there should be none outside a dev/test
-- database -- this service has no rows in flight in production yet -- but a
-- backfill keeps this migration safe to run against a database that already
-- has buffered rows rather than assuming there are none.
UPDATE alert_buffer
  SET alert_number = 'ALT' || lpad(nextval('alert_number_seq')::text, 7, '0')
  WHERE alert_number IS NULL;

ALTER TABLE alert_buffer
  ALTER COLUMN alert_number SET NOT NULL;

ALTER TABLE alert_buffer
  ADD CONSTRAINT alert_buffer_alert_number_key UNIQUE (alert_number);
