// Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package models

import "time"

// SFTPGoUser represents a user object from SFTPGo for pre-login hook.
type SFTPGoUser struct {
	// ID is the unique internal ID of the user in SFTPGo.
	ID int `json:"id"`
	// Username is the user's SFTPGo username.
	Username string `json:"username"`
}

// UserVirtualFolder represents a virtual folder for a user in SFTPGo.
type UserVirtualFolder struct {
	// Name is the display name or alias for the virtual folder.
	Name string `json:"name"`
	// VirtualPath is the path as seen by the SFTP user.
	VirtualPath string `json:"virtual_path"`
	// MappedPath is the actual system path the virtual folder points to.
	MappedPath string `json:"mapped_path"`
}

// MinimalSFTPGoUser represents the minimal SFTPGo user structure for the hook response.
type MinimalSFTPGoUser struct {
	// Username is the user's SFTPGo username.
	Username string `json:"username"`
	// HomeDir is the user's root directory in SFTPGo.
	HomeDir string `json:"home_dir"`
	// Permissions is a map of virtual paths to their allowed actions.
	Permissions map[string][]string `json:"permissions"`
	// Status defines the user's account status (1 for active).
	Status int `json:"status"`
	// VirtualFolders list additional system paths mapped to virtual paths.
	VirtualFolders []UserVirtualFolder `json:"virtual_folders,omitempty"`
}

// TokenResponse represents the structure of an OAuth2 token response.
type TokenResponse struct {
	// AccessToken is the string used to authenticate API requests.
	AccessToken string `json:"access_token"`
	// TokenType is the type of token (typically "bearer").
	TokenType string `json:"token_type"`
	// ExpiresIn is the duration in seconds until the token expires.
	ExpiresIn int `json:"expires_in"`
	// Scope is the set of permissions associated with the token.
	Scope string `json:"scope"`
}

// CustomUserExtension represents the "urn:scim:schemas:extension:custom:User" object from Asgardeo SCIM.
type CustomUserExtension struct {
	// SFTPProjects is a comma-separated list of projects assigned to the user.
	SFTPProjects string `json:"SFTPProjects"`
	// SFTPFolders is a comma-separated list of specific folders assigned to the user.
	SFTPFolders string `json:"SFTPFolders"`
}

// Meta represents the "meta" object from Asgardeo SCIM.
type Meta struct {
	// Created is the timestamp when the resource was created.
	Created time.Time `json:"created"`
	// Location is the URI where the resource is located.
	Location string `json:"location"`
	// LastModified is the timestamp when the resource was last updated.
	LastModified time.Time `json:"lastModified"`
	// ResourceType is the type of the SCIM resource (e.g., "User").
	ResourceType string `json:"resourceType"`
}

// Role represents an item in the "roles" array from Asgardeo SCIM.
type Role struct {
	// Display is the human-readable name of the role.
	Display string `json:"display"`
	// Value is the unique identifier or name of the role.
	Value string `json:"value"`
}

// AsgardeoUser represents the main user object in the Asgardeo SCIM response.
type AsgardeoUser struct {
	// Emails is a list of email addresses associated with the user.
	Emails []string `json:"emails"`
	// CustomUserExtension contains proprietary attributes for SFTP access.
	CustomUserExtension CustomUserExtension `json:"urn:scim:schemas:extension:custom:User"`
	// Meta contains resource metadata.
	Meta Meta `json:"meta"`
	// Roles is the list of roles assigned to the user.
	Roles []Role `json:"roles"`
	// ID is the unique identifier for the user in the IdP.
	ID string `json:"id"`
	// UserName is the user's login identifier.
	UserName string `json:"userName"`
}

// KeyIntRequest represents the incoming request for keyboard-interactive auth.
type KeyIntRequest struct {
	// RequestID is a unique identifier generated by SFTPGo for the auth session.
	RequestID string `json:"request_id"`
	// Step is the current sequence number of the authentication process.
	Step int `json:"step"`
	// Username is the user attempting to authenticate.
	Username string `json:"username"`
	// Answers contains the user's responses to the previous step's questions.
	Answers []string `json:"answers"`
}

// KeyIntResponse represents the response for keyboard-interactive auth.
type KeyIntResponse struct {
	// AuthResult indicates success (1), failure (-1), or incomplete (0).
	AuthResult int `json:"auth_result"`
	// Instruction is the text displayed to the user before questions.
	Instruction string `json:"instruction"`
	// Questions is the list of prompts for user input.
	Questions []string `json:"questions"`
	// CheckPassword is a flag for SFTPGo (unused in custom flows).
	CheckPassword int `json:"check_password"`
	// Echos controls whether user input is visible for each question.
	Echos []bool `json:"echos"`
}

// RequiredParam represents a detailed parameter required by an authenticator.
type RequiredParam struct {
	// ParamName is the technical name of the parameter.
	ParamName string `json:"param"`
	// ParamType is the data type (e.g., "string").
	ParamType string `json:"type"`
	// IsConfidential indicates if the value should be masked (e.g., passwords).
	IsConfidential bool `json:"confidential"`
	// DisplayName is the human-readable label for the parameter.
	DisplayName string `json:"displayName"`
	// Order is the position of the parameter in the prompt list.
	Order int `json:"order"`
}

// AuthenticatorMetadata represents the metadata section of an authenticator.
type AuthenticatorMetadata struct {
	// Params is the list of required inputs for this authenticator.
	Params []RequiredParam `json:"params"`
}

// Authenticator represents an authentication method returned by the IdP.
type Authenticator struct {
	// AuthenticatorID is the unique identifier for the auth method.
	AuthenticatorID string `json:"authenticatorId"`
	// DisplayName is the human-readable name of the auth method.
	DisplayName string `json:"authenticator"`
	// Metadata contains parameter details for the method.
	Metadata AuthenticatorMetadata `json:"metadata"`
}

// NextStep represents the next step in the authentication flow from IdP.
type NextStep struct {
	// StepType indicates the nature of the step (e.g., "AUTHENTICATOR_PROMPT").
	StepType string `json:"stepType"`
	// Authenticators is the list of available auth methods for this step.
	Authenticators []Authenticator `json:"authenticators"`
	// Messages contains any informational messages from the IdP.
	Messages []Message `json:"messages"`
}

// Message represents an item in the "messages" array from the IdP.
type Message struct {
	// Message is the informational text from the IdP.
	Message string `json:"message"`
}

// IdPResponse represents the top-level response from the IdP's authentication endpoint.
type IdPResponse struct {
	// FlowStatus indicates the state of the flow (e.g., "INCOMPLETE", "SUCCESS_COMPLETED").
	FlowStatus string `json:"flowStatus"`
	// FlowID is the unique identifier for the ongoing auth flow.
	FlowID string `json:"flowId"`
	// NextStep provides details on how to proceed if not completed.
	NextStep *NextStep `json:"nextStep"`
	// AuthorizationCode is returned upon successful authentication.
	AuthorizationCode string `json:"authorizationCode"`
	// Error contains error details if the request failed.
	Error string `json:"error"`
}

// SessionData stores state for each ongoing authentication flow.
type SessionData struct {
	// FlowID is the ID of the flow associated with the session.
	FlowID string `json:"flowId"`
	// NextStep captures the expected next interaction from the IdP.
	NextStep *NextStep `json:"nextStep"`
}

// FolderResponse is the successful response from the subscription API.
type FolderResponse struct {
	// IsValidCustomer indicates if the user has an active subscription.
	IsValidCustomer bool `json:"isValidCustomer"`
	// ProjectKeys is the list of project identifiers the user has access to.
	ProjectKeys []string `json:"projectKeys"`
}

// ErrorMessage represents a generic JSON error message.
type ErrorMessage struct {
	// Message is the descriptive error text.
	Message string `json:"message"`
}
