// Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package repository

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/wso2-open-operations/cs-tools/entity-service/internal/apierror"
	"github.com/wso2-open-operations/cs-tools/entity-service/internal/domain"
	"golang.org/x/sync/errgroup"
)

// CaseRepository defines the persistence operations for the cases table.
type CaseRepository interface {
	// CreateCase inserts a new case row. number and wso2_id are generated from
	// DB sequences; id is generated by the DB default.
	CreateCase(ctx context.Context, req domain.CreateCaseRequest) (domain.Case, error)
	// GetCaseByID returns the enriched case view for the given UUID, or a
	// NotFoundError if no matching row exists.
	GetCaseByID(ctx context.Context, id string) (domain.CaseView, error)
	// SearchCases returns a filtered, paginated slice of enriched case views
	// together with the total count of matching rows before pagination.
	// COUNT and SELECT are executed concurrently on separate pool connections.
	SearchCases(ctx context.Context, req domain.SearchCasesRequest) ([]domain.SearchCaseView, int, error)
	// CreateCaseComment inserts a new comment row for the given case.
	CreateCaseComment(ctx context.Context, req domain.CreateCaseCommentRequest) (domain.CaseComment, error)
	// SearchCaseComments returns a paginated slice of comments for the given case
	// together with the total count of matching rows before pagination.
	SearchCaseComments(ctx context.Context, req domain.SearchCaseCommentsRequest) ([]domain.CaseComment, int, error)
}

type caseRepo struct {
	db *pgxpool.Pool
}

// NewCaseRepository constructs a CaseRepository backed by the given connection pool.
func NewCaseRepository(db *pgxpool.Pool) CaseRepository {
	return &caseRepo{db: db}
}

// CreateCase implements CaseRepository.
func (r *caseRepo) CreateCase(ctx context.Context, req domain.CreateCaseRequest) (domain.Case, error) {
	const query = `
		INSERT INTO cases (
			created_by, project_id, deployment_id, deployed_product_id,
			subject, description, priority, issue_type, state
		)
		VALUES (
			$1, $2, $3, $4, $5, $6,
			$7::case_priority_enum, $8::case_issue_type_enum,
			'open'::case_state_enum
		)
		RETURNING id, number, wso2_id, created_by, project_id, deployment_id, deployed_product_id,
		          subject, description, priority, issue_type, state, created_at, updated_at, closed_at`

	var c domain.Case
	err := r.db.QueryRow(ctx, query,
		req.CreatedBy, req.ProjectID, req.DeploymentID, req.DeployedProductID,
		req.Subject, req.Description, string(req.Priority), string(req.IssueType),
	).Scan(
		&c.ID, &c.Number, &c.Wso2ID, &c.CreatedBy,
		&c.ProjectID, &c.DeploymentID, &c.DeployedProductID,
		&c.Subject, &c.Description, &c.Priority, &c.IssueType, &c.State,
		&c.CreatedAt, &c.UpdatedAt, &c.ClosedAt,
	)
	if err != nil {
		if pgErr := (*pgconn.PgError)(nil); errors.As(err, &pgErr) {
			switch pgErr.Code {
			case "23503": // foreign_key_violation — one of the referenced IDs does not exist
				return domain.Case{}, &apierror.ValidationError{Msg: "one or more referenced IDs do not exist: " + pgErr.Detail}
			case "P0001": // raise_exception from integrity triggers (deployment/project, deployed_product/deployment, catastrophic priority)
				return domain.Case{}, &apierror.ValidationError{Msg: pgErr.Message}
			}
		}
		return domain.Case{}, fmt.Errorf("create case: %w", err)
	}
	return c, nil
}

// GetCaseByID implements CaseRepository.
func (r *caseRepo) GetCaseByID(ctx context.Context, id string) (domain.CaseView, error) {
	var cv domain.CaseView
	err := r.db.QueryRow(ctx,
		`SELECT c.id, c.number, c.wso2_id,
		        c.subject, c.description, c.priority, c.issue_type, c.state,
		        c.created_at, c.updated_at, c.closed_at,
		        u.id, u.first_name || ' ' || u.last_name, u.user_name, u.email,
		        p.id, p.name,
		        d.id, d.name,
		        dp.id, prod.name || COALESCE(' ' || pv.version, '')
		 FROM cases c
		 JOIN users u ON u.id = c.created_by
		 JOIN projects p ON p.id = c.project_id
		 JOIN deployments d ON d.id = c.deployment_id
		 JOIN deployed_products dp ON dp.id = c.deployed_product_id
		 JOIN products prod ON prod.id = dp.product_id
		 LEFT JOIN product_versions pv ON pv.id = dp.product_version_id
		 WHERE c.id = $1`, id,
	).Scan(
		&cv.ID, &cv.Number, &cv.Wso2ID,
		&cv.Subject, &cv.Description, &cv.Priority, &cv.IssueType, &cv.State,
		&cv.CreatedAt, &cv.UpdatedAt, &cv.ClosedAt,
		&cv.CreatedByDetails.ID, &cv.CreatedByDetails.DisplayName, &cv.CreatedByDetails.UserID, &cv.CreatedByDetails.Email,
		&cv.ProjectDetails.ID, &cv.ProjectDetails.Name,
		&cv.DeploymentDetails.ID, &cv.DeploymentDetails.Name,
		&cv.DeployedProductDetails.ID, &cv.DeployedProductDetails.DisplayName,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.CaseView{}, &apierror.NotFoundError{Msg: "case not found"}
	}
	if err != nil {
		return domain.CaseView{}, fmt.Errorf("get case by id: %w", err)
	}
	return cv, nil
}

// CreateCaseComment implements CaseRepository.
func (r *caseRepo) CreateCaseComment(ctx context.Context, req domain.CreateCaseCommentRequest) (domain.CaseComment, error) {
	const query = `
		INSERT INTO case_comments (case_id, comment_type, body, created_by)
		VALUES ($1, $2::comment_type_enum, $3, $4)
		RETURNING id, case_id, comment_type, body, created_by, created_at`

	var c domain.CaseComment
	err := r.db.QueryRow(ctx, query,
		req.CaseID, string(req.CommentType), req.Body, req.CreatedBy,
	).Scan(&c.ID, &c.CaseID, &c.CommentType, &c.Body, &c.CreatedBy, &c.CreatedAt)
	if err != nil {
		if pgErr := (*pgconn.PgError)(nil); errors.As(err, &pgErr) {
			switch pgErr.Code {
			case "23503": // foreign_key_violation — case_id or created_by does not exist
				return domain.CaseComment{}, &apierror.ValidationError{Msg: "one or more referenced IDs do not exist: " + pgErr.Detail}
			case "P0001": // raise_exception from user-type triggers
				return domain.CaseComment{}, &apierror.ValidationError{Msg: pgErr.Message}
			}
		}
		return domain.CaseComment{}, fmt.Errorf("create case comment: %w", err)
	}
	return c, nil
}

// SearchCaseComments implements CaseRepository.
func (r *caseRepo) SearchCaseComments(ctx context.Context, req domain.SearchCaseCommentsRequest) ([]domain.CaseComment, int, error) {
	const countQuery = `SELECT COUNT(*) FROM case_comments WHERE case_id = $1`
	const dataQuery = `
		SELECT id, case_id, comment_type, body, created_by, created_at
		FROM case_comments
		WHERE case_id = $1
		ORDER BY created_at DESC, id
		LIMIT $2 OFFSET $3`

	var total int
	var comments []domain.CaseComment

	eg, egCtx := errgroup.WithContext(ctx)

	eg.Go(func() error {
		if err := r.db.QueryRow(egCtx, countQuery, req.CaseID).Scan(&total); err != nil {
			return fmt.Errorf("count case comments: %w", err)
		}
		return nil
	})

	eg.Go(func() error {
		rows, err := r.db.Query(egCtx, dataQuery, req.CaseID, req.Pagination.Limit, req.Pagination.Offset)
		if err != nil {
			return fmt.Errorf("query case comments: %w", err)
		}
		defer rows.Close()

		result := make([]domain.CaseComment, 0, req.Pagination.Limit)
		for rows.Next() {
			var c domain.CaseComment
			if err := rows.Scan(&c.ID, &c.CaseID, &c.CommentType, &c.Body, &c.CreatedBy, &c.CreatedAt); err != nil {
				return fmt.Errorf("scan case comment: %w", err)
			}
			result = append(result, c)
		}
		if err := rows.Err(); err != nil {
			return fmt.Errorf("iterate case comments: %w", err)
		}
		comments = result
		return nil
	})

	if err := eg.Wait(); err != nil {
		return nil, 0, err
	}

	return comments, total, nil
}

// SearchCases implements CaseRepository.
func (r *caseRepo) SearchCases(ctx context.Context, req domain.SearchCasesRequest) ([]domain.SearchCaseView, int, error) {
	filterArgs := []any{}
	argIdx := 1

	where := "WHERE 1=1"

	if len(req.ProjectIDs) > 0 {
		where += fmt.Sprintf(" AND c.project_id = ANY($%d::uuid[])", argIdx)
		filterArgs = append(filterArgs, req.ProjectIDs)
		argIdx++
	}

	if len(req.DeploymentIDs) > 0 {
		where += fmt.Sprintf(" AND c.deployment_id = ANY($%d::uuid[])", argIdx)
		filterArgs = append(filterArgs, req.DeploymentIDs)
		argIdx++
	}

	if len(req.DeployedProductIDs) > 0 {
		where += fmt.Sprintf(" AND c.deployed_product_id = ANY($%d::uuid[])", argIdx)
		filterArgs = append(filterArgs, req.DeployedProductIDs)
		argIdx++
	}

	if len(req.StateKeys) > 0 {
		stateStrings := make([]string, len(req.StateKeys))
		for i, s := range req.StateKeys {
			stateStrings[i] = string(s)
		}
		where += fmt.Sprintf(" AND c.state = ANY($%d::case_state_enum[])", argIdx)
		filterArgs = append(filterArgs, stateStrings)
		argIdx++
	}

	if len(req.PriorityKeys) > 0 {
		priorityStrings := make([]string, len(req.PriorityKeys))
		for i, p := range req.PriorityKeys {
			priorityStrings[i] = string(p)
		}
		where += fmt.Sprintf(" AND c.priority = ANY($%d::case_priority_enum[])", argIdx)
		filterArgs = append(filterArgs, priorityStrings)
		argIdx++
	}

	if len(req.IssueTypeKeys) > 0 {
		issueTypeStrings := make([]string, len(req.IssueTypeKeys))
		for i, it := range req.IssueTypeKeys {
			issueTypeStrings[i] = string(it)
		}
		where += fmt.Sprintf(" AND c.issue_type = ANY($%d::case_issue_type_enum[])", argIdx)
		filterArgs = append(filterArgs, issueTypeStrings)
		argIdx++
	}

	if req.SearchQuery != "" {
		escaped := strings.NewReplacer(`\`, `\\`, `%`, `\%`, `_`, `\_`).Replace(req.SearchQuery)
		pattern := "%" + escaped + "%"
		where += fmt.Sprintf(` AND (c.subject ILIKE $%d ESCAPE '\' OR c.number ILIKE $%d ESCAPE '\' OR c.wso2_id ILIKE $%d ESCAPE '\')`, argIdx, argIdx, argIdx)
		filterArgs = append(filterArgs, pattern)
		argIdx++
	}

	sortCol := "c." + string(req.SortBy.Field)
	sortDir := string(req.SortBy.Order)

	countQuery := "SELECT COUNT(*) FROM cases c " + where

	joins := `JOIN users u ON u.id = c.created_by
		 JOIN projects p ON p.id = c.project_id
		 JOIN deployments d ON d.id = c.deployment_id
		 JOIN deployed_products dp ON dp.id = c.deployed_product_id
		 JOIN products prod ON prod.id = dp.product_id
		 LEFT JOIN product_versions pv ON pv.id = dp.product_version_id`

	dataQuery := fmt.Sprintf(
		`SELECT c.id, c.number, c.wso2_id,
		        c.subject, c.description, c.priority, c.issue_type, c.state,
		        c.created_at, c.updated_at, c.closed_at,
		        u.id, u.first_name || ' ' || u.last_name, u.user_name, u.email,
		        p.id, p.name,
		        d.id, d.name,
		        dp.id, prod.name || COALESCE(' ' || pv.version, '')
		 FROM cases c %s %s
		 ORDER BY %s %s NULLS LAST, c.id
		 LIMIT $%d OFFSET $%d`,
		joins, where, sortCol, sortDir, argIdx, argIdx+1,
	)
	dataArgs := append(append([]any{}, filterArgs...), req.Pagination.Limit, req.Pagination.Offset)

	var total int
	var cases []domain.SearchCaseView

	eg, egCtx := errgroup.WithContext(ctx)

	eg.Go(func() error {
		if err := r.db.QueryRow(egCtx, countQuery, filterArgs...).Scan(&total); err != nil {
			return fmt.Errorf("count cases: %w", err)
		}
		return nil
	})

	eg.Go(func() error {
		rows, err := r.db.Query(egCtx, dataQuery, dataArgs...)
		if err != nil {
			return fmt.Errorf("query cases: %w", err)
		}
		defer rows.Close()

		result := make([]domain.SearchCaseView, 0, req.Pagination.Limit)
		for rows.Next() {
			var cv domain.SearchCaseView
			var ignoredDisplayName, ignoredUserID string
			if err := rows.Scan(
				&cv.ID, &cv.Number, &cv.Wso2ID,
				&cv.Subject, &cv.Description, &cv.Priority, &cv.IssueType, &cv.State,
				&cv.CreatedAt, &cv.UpdatedAt, &cv.ClosedAt,
				&cv.CreatedBy.ID, &ignoredDisplayName, &ignoredUserID, &cv.CreatedBy.Email,
				&cv.ProjectDetails.ID, &cv.ProjectDetails.Name,
				&cv.DeploymentDetails.ID, &cv.DeploymentDetails.Name,
				&cv.DeployedProductDetails.ID, &cv.DeployedProductDetails.DisplayName,
			); err != nil {
				return fmt.Errorf("scan case: %w", err)
			}
			result = append(result, cv)
		}
		if err := rows.Err(); err != nil {
			return fmt.Errorf("iterate cases: %w", err)
		}
		cases = result
		return nil
	})

	if err := eg.Wait(); err != nil {
		return nil, 0, err
	}

	return cases, total, nil
}
