// Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package repository

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/wso2-open-operations/cs-tools/entity-service/internal/apierror"
	"github.com/wso2-open-operations/cs-tools/entity-service/internal/domain"
	"golang.org/x/sync/errgroup"
)

// parentRefTypeCase is the CaseNumberRef.Type value for a parent that is itself a case.
// Addressable because CaseNumberRef.Type is an optional (pointer) field.
var parentRefTypeCase = "case"

// CaseRepository defines the persistence operations for the cases table.
type CaseRepository interface {
	// CreateCase inserts a new case row. number and internal_id are generated from
	// DB sequences; id is generated by the DB default.
	CreateCase(ctx context.Context, req domain.CreateCaseRequest) (domain.Case, error)
	// GetCaseByID returns the enriched case view for the given UUID, or a
	// NotFoundError if no matching row exists.
	GetCaseByID(ctx context.Context, id string) (domain.CaseView, error)
	// SearchCases returns a filtered, paginated slice of enriched case views
	// together with the total count of matching rows before pagination.
	// COUNT and SELECT are executed concurrently on separate pool connections.
	SearchCases(ctx context.Context, req domain.SearchCasesRequest) ([]domain.SearchCaseView, int, error)
	// CreateCaseComment inserts a new comment row for the given case.
	CreateCaseComment(ctx context.Context, req domain.CreateCaseCommentRequest) (domain.CaseComment, error)
	// SearchCaseComments returns a paginated slice of comments for the given case
	// together with the total count of matching rows before pagination.
	SearchCaseComments(ctx context.Context, req domain.SearchCaseCommentsRequest) ([]domain.CaseComment, int, error)
	// UpdateCase updates the state and/or priority of the case identified by
	// req.ID. closed_at is set to NOW() when transitioning to closed.
	//
	// previousSeverity is the case's severity as it stood immediately before
	// this update. When req.Severity is nil, severity can't have changed at
	// all, so this just equals the returned domain.Case.Severity — no extra
	// work needed. When req.Severity is set, this runs inside a transaction
	// that locks the row (SELECT ... FOR UPDATE) before reading its prior
	// severity and applying the update, so previousSeverity is accurate even
	// under a concurrent update to the same case: a plain separate
	// read-then-write (what this used to do) could either miss a genuine
	// LOW-severity-boundary crossing or double-detect one, depending on how
	// two concurrent updates interleave — see caseService.
	// detectBillableStatusChange, the sole caller that needs this value, and
	// the CodeRabbit finding on PR #1683 this fixes.
	//
	// Returns a NotFoundError if no matching row exists.
	UpdateCase(ctx context.Context, req domain.UpdateCaseRequest) (c domain.Case, previousSeverity domain.CaseSeverity, err error)
	// CreateCaseAttachment inserts a new attachment metadata row for the case
	// identified by req.ReferenceID. req.StorageKey must be non-nil: this data
	// source stores file bytes externally in SFTPGo, never inline in Postgres.
	// Returns a ValidationError if req.ReferenceID does not match an existing case.
	CreateCaseAttachment(ctx context.Context, req domain.CreateAttachmentRequest) (domain.Attachment, error)
	// SearchCaseAttachments returns a paginated slice of attachments for the given
	// case, most recently created first, together with the total matching count.
	SearchCaseAttachments(ctx context.Context, caseID string, pagination domain.Pagination) ([]domain.Attachment, int, error)
	// GetCaseAttachmentByID returns the attachment identified by id.
	// Returns a NotFoundError if no matching row exists.
	GetCaseAttachmentByID(ctx context.Context, id string) (domain.Attachment, error)
	// DeleteCaseAttachment permanently removes the attachment metadata row
	// identified by id. It does not delete the backing SFTPGo file -- that
	// remains the downstream CSM backend's responsibility.
	// Returns a NotFoundError if no matching row exists.
	DeleteCaseAttachment(ctx context.Context, id string) error
	// UpdateCaseAttachmentName renames the attachment identified by id and
	// records who did it. Returns a NotFoundError if no matching row exists.
	UpdateCaseAttachmentName(ctx context.Context, id, name, updatedBy string) (updatedOn time.Time, err error)
	// ConfirmCaseAttachment atomically transitions the attachment identified
	// by id from status 'pending' to 'complete'. The WHERE clause's
	// "AND status = 'pending'" guard is the concurrency safety net: if two
	// confirm calls race, only one affects a row. Returns a ConflictError
	// (not a silent no-op) if the row is not currently 'pending' -- including
	// when it doesn't exist, since by the time this is called the caller has
	// already resolved the row via GetCaseAttachmentByID and any mismatch
	// here means it changed state concurrently.
	ConfirmCaseAttachment(ctx context.Context, id string) (domain.Attachment, error)
}

type caseRepo struct {
	db *pgxpool.Pool
}

// NewCaseRepository constructs a CaseRepository backed by the given connection pool.
func NewCaseRepository(db *pgxpool.Pool) CaseRepository {
	return &caseRepo{db: db}
}

// CreateCase implements CaseRepository.
func (r *caseRepo) CreateCase(ctx context.Context, req domain.CreateCaseRequest) (domain.Case, error) {
	const query = `
		INSERT INTO cases (
			created_by, project_id, deployment_id, deployed_product_id,
			type, subject, description, severity, issue_type, state
		)
		VALUES (
			$1, $2, $3, $4,
			$5::case_type_enum, $6, $7,
			$8::case_severity_enum, $9::case_issue_type_enum,
			'open'::case_state_enum
		)
		RETURNING id, number, internal_id, created_by, project_id, deployment_id, deployed_product_id,
		          subject, description, severity, issue_type, state, created_at, updated_at, closed_at`

	var c domain.Case
	err := r.db.QueryRow(ctx, query,
		req.CreatedBy, req.ProjectID, req.DeploymentID, req.DeployedProductID,
		req.Type, req.Subject, req.Description, string(req.Severity), string(req.IssueType),
	).Scan(
		&c.ID, &c.Number, &c.InternalID, &c.CreatedBy,
		&c.ProjectID, &c.DeploymentID, &c.DeployedProductID,
		&c.Subject, &c.Description, &c.Severity, &c.IssueType, &c.State,
		&c.CreatedOn, &c.UpdatedOn, &c.ClosedOn,
	)
	if err != nil {
		if pgErr := (*pgconn.PgError)(nil); errors.As(err, &pgErr) {
			switch pgErr.Code {
			case "23503": // foreign_key_violation — one of the referenced IDs does not exist
				return domain.Case{}, &apierror.ValidationError{Msg: "one or more referenced IDs do not exist: " + pgErr.Detail}
			case "P0001": // raise_exception from integrity triggers (deployment/project, deployed_product/deployment, catastrophic priority)
				return domain.Case{}, &apierror.ValidationError{Msg: pgErr.Message}
			}
		}
		return domain.Case{}, fmt.Errorf("create case: %w", err)
	}
	return c, nil
}

// GetCaseByID implements CaseRepository.
func (r *caseRepo) GetCaseByID(ctx context.Context, id string) (domain.CaseView, error) {
	var cv domain.CaseView
	var (
		aeID, aeName                         *string
		pcID, pcNum                          *string
		rcID, rcNum                          *string
		accountID, accountName, accountTier  string
		workState                            *string
		depID, depName                       string
		dpID, dpDisplayName                  string
		prodID, prodName                     string
		creatorID, creatorName, creatorEmail string
	)
	err := r.db.QueryRow(ctx,
		`SELECT c.id, c.number, c.internal_id,
		        c.subject, c.description, c.severity, c.issue_type, c.state, c.work_state,
		        c.created_at, c.updated_at, c.closed_at,
		        u.id, u.first_name || ' ' || u.last_name, u.email,
		        p.id, p.name,
		        d.id, d.name,
		        dp.id, prod.name || COALESCE(' ' || pv.version, ''),
		        prod.id, prod.name,
		        a.id, a.name, a.tier,
		        ae.id, ae.first_name || ' ' || ae.last_name,
		        pc.id, pc.number,
		        rc.id, rc.number
		 FROM cases c
		 JOIN users u ON u.id = c.created_by
		 JOIN projects p ON p.id = c.project_id
		 JOIN accounts a ON a.id = p.account_id
		 JOIN deployments d ON d.id = c.deployment_id
		 JOIN deployed_products dp ON dp.id = c.deployed_product_id
		 JOIN products prod ON prod.id = dp.product_id
		 LEFT JOIN product_versions pv ON pv.id = dp.product_version_id
		 LEFT JOIN users ae ON ae.id = c.assigned_engineer
		 LEFT JOIN cases pc ON pc.id = c.parent_case_id
		 LEFT JOIN cases rc ON rc.id = c.related_case_id
		 WHERE c.id = $1`, id,
	).Scan(
		&cv.ID, &cv.Number, &cv.InternalID,
		&cv.Subject, &cv.Description, &cv.Severity, &cv.IssueType, &cv.State, &workState,
		&cv.CreatedOn, &cv.UpdatedOn, &cv.ClosedOn,
		&creatorID, &creatorName, &creatorEmail,
		&cv.ProjectDetails.ID, &cv.ProjectDetails.Name,
		&depID, &depName,
		&dpID, &dpDisplayName,
		&prodID, &prodName,
		&accountID, &accountName, &accountTier,
		&aeID, &aeName,
		&pcID, &pcNum,
		&rcID, &rcNum,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.CaseView{}, &apierror.NotFoundError{Msg: "case not found"}
	}
	if err != nil {
		return domain.CaseView{}, fmt.Errorf("get case by id: %w", err)
	}
	cv.DeploymentDetails = &domain.EntityRef{ID: depID, Name: depName}
	cv.DeployedProductDetails = &domain.DeployedProductRef{
		ID:          &dpID,
		DisplayName: &dpDisplayName,
		// The catalogue product the deployed instance was created from. Both
		// joins are inner, so this data source always has one when it has a
		// deployed product.
		Product: &domain.EntityRef{ID: prodID, Name: prodName},
	}
	cv.AccountDetails = &domain.AccountRef{ID: accountID, Name: accountName, Type: accountTier}
	if workState != nil {
		ws := domain.CaseWorkState(*workState)
		cv.WorkState = &ws
	}
	cv.CreatedBy = domain.NewUserReference(creatorID, creatorEmail, creatorName)
	if aeID != nil {
		// This data source stores no email on the assignee join, only id and name.
		cv.AssignedEngineer = domain.NewUserReference(*aeID, "", *aeName)
	}
	if pcID != nil {
		// cases.parent_case_id is a foreign key into cases, so a parent resolved from
		// this data source is always another case -- state that explicitly rather than
		// leaving Type nil, which means "kind unknown" and must not be routed as a case.
		cv.ParentCase = &domain.CaseNumberRef{ID: *pcID, Number: *pcNum, Type: &parentRefTypeCase}
	}
	if rcID != nil {
		cv.RelatedCase = &domain.CaseNumberRef{ID: *rcID, Number: *rcNum}
	}
	return cv, nil
}

// CreateCaseComment implements CaseRepository.
func (r *caseRepo) CreateCaseComment(ctx context.Context, req domain.CreateCaseCommentRequest) (domain.CaseComment, error) {
	const query = `
		INSERT INTO case_comments (case_id, type, content, created_by)
		VALUES ($1, $2::comment_type_enum, $3, $4)
		RETURNING id, case_id, type, content, created_by, created_at`

	var c domain.CaseComment
	var createdByID string
	err := r.db.QueryRow(ctx, query,
		req.CaseID, string(req.Type), req.Content, req.CreatedBy,
	).Scan(&c.ID, &c.CaseID, &c.Type, &c.Content, &createdByID, &c.CreatedOn)
	if err != nil {
		if pgErr := (*pgconn.PgError)(nil); errors.As(err, &pgErr) {
			switch pgErr.Code {
			case "23503": // foreign_key_violation — case_id or created_by does not exist
				return domain.CaseComment{}, &apierror.ValidationError{Msg: "one or more referenced IDs do not exist: " + pgErr.Detail}
			case "P0001": // raise_exception from user-type triggers
				return domain.CaseComment{}, &apierror.ValidationError{Msg: pgErr.Message}
			}
		}
		return domain.CaseComment{}, fmt.Errorf("create case comment: %w", err)
	}
	// The insert returns only the author's id; email and display name would need
	// a further join, so the reference carries the id alone.
	c.CreatedBy = domain.NewUserReference(createdByID, "", "")
	return c, nil
}

// SearchCaseComments implements CaseRepository.
func (r *caseRepo) SearchCaseComments(ctx context.Context, req domain.SearchCaseCommentsRequest) ([]domain.CaseComment, int, error) {
	args := []any{req.CaseID}
	typeFilter := ""
	if req.Filters != nil && req.Filters.Type != nil {
		args = append(args, string(*req.Filters.Type))
		typeFilter = fmt.Sprintf(" AND cc.type = $%d::comment_type_enum", len(args))
	}

	countQuery := `SELECT COUNT(*) FROM case_comments cc WHERE cc.case_id = $1` + typeFilter
	dataQuery := fmt.Sprintf(`
		SELECT cc.id, cc.case_id, cc.type, cc.content,
		       u.id, u.email,
		       TRIM(u.first_name || ' ' || u.last_name) AS full_name,
		       cc.created_at
		FROM case_comments cc
		JOIN users u ON u.id = cc.created_by
		WHERE cc.case_id = $1%s
		ORDER BY cc.created_at DESC, cc.id
		LIMIT $%d OFFSET $%d`, typeFilter, len(args)+1, len(args)+2)

	dataArgs := append(args, req.Pagination.Limit, req.Pagination.Offset)

	var total int
	var comments []domain.CaseComment

	eg, egCtx := errgroup.WithContext(ctx)

	eg.Go(func() error {
		if err := r.db.QueryRow(egCtx, countQuery, args...).Scan(&total); err != nil {
			return fmt.Errorf("count case comments: %w", err)
		}
		return nil
	})

	eg.Go(func() error {
		rows, err := r.db.Query(egCtx, dataQuery, dataArgs...)
		if err != nil {
			return fmt.Errorf("query case comments: %w", err)
		}
		defer rows.Close()

		result := make([]domain.CaseComment, 0, req.Pagination.Limit)
		for rows.Next() {
			var c domain.CaseComment
			var authorID, authorEmail, authorName string
			if err := rows.Scan(
				&c.ID, &c.CaseID, &c.Type, &c.Content,
				&authorID, &authorEmail, &authorName, &c.CreatedOn,
			); err != nil {
				return fmt.Errorf("scan case comment: %w", err)
			}
			c.CreatedBy = domain.NewUserReference(authorID, authorEmail, authorName)
			result = append(result, c)
		}
		if err := rows.Err(); err != nil {
			return fmt.Errorf("iterate case comments: %w", err)
		}
		comments = result
		return nil
	})

	if err := eg.Wait(); err != nil {
		return nil, 0, err
	}

	return comments, total, nil
}

// updateCaseQuery is shared by both branches of UpdateCase below.
const updateCaseQuery = `
	UPDATE cases
	SET state      = CASE WHEN $2 <> '' THEN $2::case_state_enum ELSE state END,
	    severity   = CASE WHEN $3 <> '' THEN $3::case_severity_enum ELSE severity END,
	    work_state = CASE WHEN $4 <> '' THEN $4::case_work_state_enum ELSE work_state END,
	    updated_at = NOW(),
	    closed_at  = CASE WHEN $2 = 'closed' THEN NOW() WHEN $2 <> '' AND $2 <> 'closed' THEN NULL ELSE closed_at END
	WHERE id = $1
	RETURNING id, number, internal_id, created_by, project_id, deployment_id, deployed_product_id,
	          subject, description, severity, issue_type, state, work_state, created_at, updated_at, closed_at`

// scanUpdatedCase is shared by both branches of UpdateCase below.
func scanUpdatedCase(row pgx.Row) (domain.Case, error) {
	var c domain.Case
	var workStateRaw *string
	if err := row.Scan(
		&c.ID, &c.Number, &c.InternalID, &c.CreatedBy,
		&c.ProjectID, &c.DeploymentID, &c.DeployedProductID,
		&c.Subject, &c.Description, &c.Severity, &c.IssueType, &c.State, &workStateRaw,
		&c.CreatedOn, &c.UpdatedOn, &c.ClosedOn,
	); err != nil {
		return domain.Case{}, err
	}
	if workStateRaw != nil {
		ws := domain.CaseWorkState(*workStateRaw)
		c.WorkState = &ws
	}
	return c, nil
}

// UpdateCase implements CaseRepository.
func (r *caseRepo) UpdateCase(ctx context.Context, req domain.UpdateCaseRequest) (domain.Case, domain.CaseSeverity, error) {
	state := ""
	if req.State != nil {
		state = string(*req.State)
	}
	severity := ""
	if req.Severity != nil {
		severity = string(*req.Severity)
	}
	workState := ""
	if req.WorkState != nil {
		workState = string(*req.WorkState)
	}

	// req.Severity == nil: severity can't change, so there's nothing to
	// race on — skip the transaction/lock overhead entirely.
	if req.Severity == nil {
		c, err := scanUpdatedCase(r.db.QueryRow(ctx, updateCaseQuery, req.ID, state, severity, workState))
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.Case{}, "", &apierror.NotFoundError{Msg: "case not found"}
		}
		if err != nil {
			return domain.Case{}, "", fmt.Errorf("update case: %w", err)
		}
		return c, c.Severity, nil
	}

	// req.Severity != nil: lock the row first so the previous severity this
	// returns is accurate even under a concurrent update to the same case —
	// see this method's own interface doc comment for why that matters.
	tx, err := r.db.Begin(ctx)
	if err != nil {
		return domain.Case{}, "", fmt.Errorf("update case: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	var previousSeverity domain.CaseSeverity
	err = tx.QueryRow(ctx, `SELECT severity FROM cases WHERE id = $1 FOR UPDATE`, req.ID).Scan(&previousSeverity)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.Case{}, "", &apierror.NotFoundError{Msg: "case not found"}
	}
	if err != nil {
		return domain.Case{}, "", fmt.Errorf("update case: lock row: %w", err)
	}

	c, err := scanUpdatedCase(tx.QueryRow(ctx, updateCaseQuery, req.ID, state, severity, workState))
	if err != nil {
		return domain.Case{}, "", fmt.Errorf("update case: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return domain.Case{}, "", fmt.Errorf("update case: commit tx: %w", err)
	}
	return c, previousSeverity, nil
}

// CreateCaseAttachment implements CaseRepository.
func (r *caseRepo) CreateCaseAttachment(ctx context.Context, req domain.CreateAttachmentRequest) (domain.Attachment, error) {
	const query = `
		INSERT INTO case_attachments (case_id, storage_key, filename, mime_type, size_bytes, description, uploaded_by, status)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id, case_id, storage_key, filename, mime_type, size_bytes, description, uploaded_by, created_at, status`

	var (
		a            domain.Attachment
		storageKey   string
		uploadedByID string
	)
	err := r.db.QueryRow(ctx, query,
		req.ReferenceID, req.StorageKey, req.Name, req.Type, req.SizeBytes, req.Description, req.CreatedBy, req.Status,
	).Scan(
		&a.ID, &a.ReferenceID, &storageKey, &a.Name, &a.Type, &a.SizeBytes, &a.Description,
		&uploadedByID, &a.CreatedOn, &a.Status,
	)
	if err != nil {
		if pgErr := (*pgconn.PgError)(nil); errors.As(err, &pgErr) {
			switch pgErr.Code {
			case "23503": // foreign_key_violation — case_id or uploaded_by does not exist
				return domain.Attachment{}, &apierror.ValidationError{Msg: "one or more referenced IDs do not exist: " + pgErr.Detail}
			case "23514": // check_violation — e.g. size_bytes <= 0 or an invalid status
				return domain.Attachment{}, &apierror.ValidationError{Msg: pgErr.Message}
			}
		}
		return domain.Attachment{}, fmt.Errorf("create case attachment: %w", err)
	}
	a.ReferenceType = domain.ReferenceTypeCase
	a.StorageKey = &storageKey
	// The insert returns only the uploader's id; email and display name would
	// need a further join, so the reference carries the id alone, same as
	// CreateCaseComment above.
	a.CreatedBy = domain.NewUserReference(uploadedByID, "", "")
	return a, nil
}

// ConfirmCaseAttachment implements CaseRepository.
func (r *caseRepo) ConfirmCaseAttachment(ctx context.Context, id string) (domain.Attachment, error) {
	const query = `
		UPDATE case_attachments
		SET status = 'complete', updated_at = NOW()
		WHERE id = $1 AND status = 'pending'
		RETURNING id, case_id, storage_key, filename, mime_type, size_bytes, description, uploaded_by, created_at, status`

	var (
		a            domain.Attachment
		storageKey   string
		uploadedByID string
	)
	err := r.db.QueryRow(ctx, query, id).Scan(
		&a.ID, &a.ReferenceID, &storageKey, &a.Name, &a.Type, &a.SizeBytes, &a.Description,
		&uploadedByID, &a.CreatedOn, &a.Status,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.Attachment{}, &apierror.ConflictError{Msg: "attachment is not pending (it may already be confirmed, or was confirmed/deleted concurrently)"}
	}
	if err != nil {
		return domain.Attachment{}, fmt.Errorf("confirm case attachment: %w", err)
	}
	a.ReferenceType = domain.ReferenceTypeCase
	a.StorageKey = &storageKey
	a.CreatedBy = domain.NewUserReference(uploadedByID, "", "")
	return a, nil
}

// SearchCaseAttachments implements CaseRepository.
//
// Both queries filter to status = 'complete' -- see the doc comment on
// CaseService.SearchCaseAttachments for why pending (still-uploading) rows
// are excluded from the default list/search response rather than shown with
// a visible status.
func (r *caseRepo) SearchCaseAttachments(ctx context.Context, caseID string, pagination domain.Pagination) ([]domain.Attachment, int, error) {
	const countQuery = `SELECT COUNT(*) FROM case_attachments WHERE case_id = $1 AND status = 'complete'`
	const dataQuery = `
		SELECT ca.id, ca.case_id, ca.filename, ca.mime_type, ca.size_bytes, ca.description,
		       u.id, u.email, TRIM(u.first_name || ' ' || u.last_name) AS full_name,
		       ca.created_at, ca.storage_key, ca.status
		FROM case_attachments ca
		JOIN users u ON u.id = ca.uploaded_by
		WHERE ca.case_id = $1 AND ca.status = 'complete'
		ORDER BY ca.created_at DESC, ca.id
		LIMIT $2 OFFSET $3`

	var total int
	var attachments []domain.Attachment

	eg, egCtx := errgroup.WithContext(ctx)

	eg.Go(func() error {
		if err := r.db.QueryRow(egCtx, countQuery, caseID).Scan(&total); err != nil {
			return fmt.Errorf("count case attachments: %w", err)
		}
		return nil
	})

	eg.Go(func() error {
		rows, err := r.db.Query(egCtx, dataQuery, caseID, pagination.Limit, pagination.Offset)
		if err != nil {
			return fmt.Errorf("query case attachments: %w", err)
		}
		defer rows.Close()

		result := make([]domain.Attachment, 0, pagination.Limit)
		for rows.Next() {
			var (
				a                         domain.Attachment
				uploaderID, uploaderEmail string
				uploaderName, storageKey  string
			)
			if err := rows.Scan(
				&a.ID, &a.ReferenceID, &a.Name, &a.Type, &a.SizeBytes, &a.Description,
				&uploaderID, &uploaderEmail, &uploaderName, &a.CreatedOn, &storageKey, &a.Status,
			); err != nil {
				return fmt.Errorf("scan case attachment: %w", err)
			}
			a.ReferenceType = domain.ReferenceTypeCase
			a.CreatedBy = domain.NewUserReference(uploaderID, uploaderEmail, uploaderName)
			a.StorageKey = &storageKey
			result = append(result, a)
		}
		if err := rows.Err(); err != nil {
			return fmt.Errorf("iterate case attachments: %w", err)
		}
		attachments = result
		return nil
	})

	if err := eg.Wait(); err != nil {
		return nil, 0, err
	}

	return attachments, total, nil
}

// GetCaseAttachmentByID implements CaseRepository.
//
// Unlike SearchCaseAttachments, this intentionally does not filter by status:
// a direct id lookup must return a 'pending' row too, since that's how the
// confirm step resolves the row it's about to transition, and how an
// uploader can check on their own in-flight upload. See the doc comment on
// CaseService.SearchCaseAttachments for the read-path status decision.
func (r *caseRepo) GetCaseAttachmentByID(ctx context.Context, id string) (domain.Attachment, error) {
	const query = `
		SELECT ca.id, ca.case_id, ca.filename, ca.mime_type, ca.size_bytes, ca.description,
		       u.id, u.email, TRIM(u.first_name || ' ' || u.last_name) AS full_name,
		       ca.created_at, ca.storage_key, ca.status
		FROM case_attachments ca
		JOIN users u ON u.id = ca.uploaded_by
		WHERE ca.id = $1`

	var (
		a                         domain.Attachment
		uploaderID, uploaderEmail string
		uploaderName, storageKey  string
	)
	err := r.db.QueryRow(ctx, query, id).Scan(
		&a.ID, &a.ReferenceID, &a.Name, &a.Type, &a.SizeBytes, &a.Description,
		&uploaderID, &uploaderEmail, &uploaderName, &a.CreatedOn, &storageKey, &a.Status,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.Attachment{}, &apierror.NotFoundError{Msg: "attachment not found"}
	}
	if err != nil {
		return domain.Attachment{}, fmt.Errorf("get case attachment by id: %w", err)
	}
	a.ReferenceType = domain.ReferenceTypeCase
	a.CreatedBy = domain.NewUserReference(uploaderID, uploaderEmail, uploaderName)
	a.StorageKey = &storageKey
	return a, nil
}

// DeleteCaseAttachment implements CaseRepository.
func (r *caseRepo) DeleteCaseAttachment(ctx context.Context, id string) error {
	tag, err := r.db.Exec(ctx, `DELETE FROM case_attachments WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("delete case attachment: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return &apierror.NotFoundError{Msg: "attachment not found"}
	}
	return nil
}

// UpdateCaseAttachmentName implements CaseRepository.
func (r *caseRepo) UpdateCaseAttachmentName(ctx context.Context, id, name, updatedBy string) (time.Time, error) {
	const query = `
		UPDATE case_attachments
		SET filename = $2, updated_at = NOW(), updated_by = $3
		WHERE id = $1
		RETURNING updated_at`

	var updatedOn time.Time
	err := r.db.QueryRow(ctx, query, id, name, updatedBy).Scan(&updatedOn)
	if errors.Is(err, pgx.ErrNoRows) {
		return time.Time{}, &apierror.NotFoundError{Msg: "attachment not found"}
	}
	if err != nil {
		if pgErr := (*pgconn.PgError)(nil); errors.As(err, &pgErr) && pgErr.Code == "23503" {
			return time.Time{}, &apierror.ValidationError{Msg: "one or more referenced IDs do not exist: " + pgErr.Detail}
		}
		return time.Time{}, fmt.Errorf("update case attachment name: %w", err)
	}
	return updatedOn, nil
}

// pgSortColMap maps domain CaseSortField values to Postgres column expressions.
var pgSortColMap = map[domain.CaseSortField]string{
	domain.CaseSortFieldCreatedOn: "c.created_at",
	domain.CaseSortFieldUpdatedOn: "c.updated_at",
	domain.CaseSortFieldSeverity:  "c.severity",
	domain.CaseSortFieldState:     "c.state",
}

// SearchCases implements CaseRepository.
func (r *caseRepo) SearchCases(ctx context.Context, req domain.SearchCasesRequest) ([]domain.SearchCaseView, int, error) {
	filterArgs := []any{}
	argIdx := 1

	where := "WHERE 1=1"

	if len(req.Parsed.Types) > 0 {
		where += fmt.Sprintf(" AND c.type = ANY($%d::case_type_enum[])", argIdx)
		filterArgs = append(filterArgs, req.Parsed.Types)
		argIdx++
	}

	if len(req.Parsed.ProjectIDs) > 0 {
		where += fmt.Sprintf(" AND c.project_id = ANY($%d::uuid[])", argIdx)
		filterArgs = append(filterArgs, req.Parsed.ProjectIDs)
		argIdx++
	}

	if len(req.Parsed.DeploymentIDs) > 0 {
		where += fmt.Sprintf(" AND c.deployment_id = ANY($%d::uuid[])", argIdx)
		filterArgs = append(filterArgs, req.Parsed.DeploymentIDs)
		argIdx++
	}

	if len(req.Parsed.States) > 0 {
		stateStrings := make([]string, len(req.Parsed.States))
		for i, s := range req.Parsed.States {
			stateStrings[i] = string(s)
		}
		where += fmt.Sprintf(" AND c.state = ANY($%d::case_state_enum[])", argIdx)
		filterArgs = append(filterArgs, stateStrings)
		argIdx++
	}

	if len(req.Parsed.Severities) > 0 {
		severityStrings := make([]string, len(req.Parsed.Severities))
		for i, s := range req.Parsed.Severities {
			severityStrings[i] = string(s)
		}
		where += fmt.Sprintf(" AND c.severity = ANY($%d::case_severity_enum[])", argIdx)
		filterArgs = append(filterArgs, severityStrings)
		argIdx++
	}

	if len(req.Parsed.IssueTypes) > 0 {
		issueTypeStrings := make([]string, len(req.Parsed.IssueTypes))
		for i, it := range req.Parsed.IssueTypes {
			issueTypeStrings[i] = string(it)
		}
		where += fmt.Sprintf(" AND c.issue_type = ANY($%d::case_issue_type_enum[])", argIdx)
		filterArgs = append(filterArgs, issueTypeStrings)
		argIdx++
	}

	if len(req.Parsed.EngagementTypes) > 0 {
		engTypeStrings := make([]string, len(req.Parsed.EngagementTypes))
		for i, et := range req.Parsed.EngagementTypes {
			engTypeStrings[i] = string(et)
		}
		where += fmt.Sprintf(" AND c.engagement_type = ANY($%d::engagement_type_enum[])", argIdx)
		filterArgs = append(filterArgs, engTypeStrings)
		argIdx++
	}

	if len(req.Parsed.CreatedBy) > 0 {
		where += fmt.Sprintf(" AND u.email = ANY($%d)", argIdx)
		filterArgs = append(filterArgs, req.Parsed.CreatedBy)
		argIdx++
	}

	if len(req.Parsed.WorkStates) > 0 {
		workStateStrings := make([]string, len(req.Parsed.WorkStates))
		for i, ws := range req.Parsed.WorkStates {
			workStateStrings[i] = string(ws)
		}
		where += fmt.Sprintf(" AND c.work_state = ANY($%d::case_work_state_enum[])", argIdx)
		filterArgs = append(filterArgs, workStateStrings)
		argIdx++
	}

	if len(req.Parsed.AssignedUserIDs) > 0 {
		where += fmt.Sprintf(" AND c.assigned_engineer = ANY($%d::uuid[])", argIdx)
		filterArgs = append(filterArgs, req.Parsed.AssignedUserIDs)
		argIdx++
	}

	if req.Parsed.ClosedStartDate != nil {
		where += fmt.Sprintf(" AND c.closed_at >= $%d", argIdx)
		filterArgs = append(filterArgs, req.Parsed.ClosedStartDate)
		argIdx++
	}
	if req.Parsed.ClosedEndDate != nil {
		where += fmt.Sprintf(" AND c.closed_at <= $%d", argIdx)
		filterArgs = append(filterArgs, req.Parsed.ClosedEndDate)
		argIdx++
	}
	if req.Parsed.StartCreatedDate != nil {
		where += fmt.Sprintf(" AND c.created_at >= $%d", argIdx)
		filterArgs = append(filterArgs, req.Parsed.StartCreatedDate)
		argIdx++
	}
	if req.Parsed.EndCreatedDate != nil {
		where += fmt.Sprintf(" AND c.created_at <= $%d", argIdx)
		filterArgs = append(filterArgs, req.Parsed.EndCreatedDate)
		argIdx++
	}
	if req.Parsed.StartUpdatedDate != nil {
		where += fmt.Sprintf(" AND c.updated_at >= $%d", argIdx)
		filterArgs = append(filterArgs, req.Parsed.StartUpdatedDate)
		argIdx++
	}
	if req.Parsed.EndUpdatedDate != nil {
		where += fmt.Sprintf(" AND c.updated_at <= $%d", argIdx)
		filterArgs = append(filterArgs, req.Parsed.EndUpdatedDate)
		argIdx++
	}

	if req.Filters.SearchQuery != "" {
		escaped := strings.NewReplacer(`\`, `\\`, `%`, `\%`, `_`, `\_`).Replace(req.Filters.SearchQuery)
		pattern := "%" + escaped + "%"
		where += fmt.Sprintf(` AND (c.subject ILIKE $%d ESCAPE '\' OR c.number ILIKE $%d ESCAPE '\' OR c.internal_id ILIKE $%d ESCAPE '\')`, argIdx, argIdx, argIdx)
		filterArgs = append(filterArgs, pattern)
		argIdx++
	}

	sortCol := pgSortColMap[req.SortBy.Field]
	sortDir := string(req.SortBy.Order)

	joins := `JOIN users u ON u.id = c.created_by
		 JOIN projects p ON p.id = c.project_id
		 JOIN deployments d ON d.id = c.deployment_id
		 JOIN deployed_products dp ON dp.id = c.deployed_product_id
		 JOIN products prod ON prod.id = dp.product_id
		 LEFT JOIN product_versions pv ON pv.id = dp.product_version_id
		 LEFT JOIN users ae ON ae.id = c.assigned_engineer
		 LEFT JOIN cases pc ON pc.id = c.parent_case_id
		 LEFT JOIN cases rc ON rc.id = c.related_case_id`

	countQuery := "SELECT COUNT(*) FROM cases c " + joins + " " + where

	dataQuery := fmt.Sprintf(
		`SELECT c.id, c.number, c.internal_id,
		        c.type, c.subject, c.description, c.severity, c.issue_type, c.state,
		        c.engagement_type, c.work_state, c.created_at, c.updated_at,
		        u.email,
		        p.id, p.name,
		        d.id, d.name,
		        dp.id, prod.name || COALESCE(' ' || pv.version, ''),
		        prod.id, prod.name,
		        ae.id, ae.first_name || ' ' || ae.last_name,
		        pc.id, pc.number,
		        rc.id, rc.number
		 FROM cases c %s %s
		 ORDER BY %s %s NULLS LAST, c.id
		 LIMIT $%d OFFSET $%d`,
		joins, where, sortCol, sortDir, argIdx, argIdx+1,
	)
	dataArgs := append(append([]any{}, filterArgs...), req.Pagination.Limit, req.Pagination.Offset)

	var total int
	var cases []domain.SearchCaseView

	eg, egCtx := errgroup.WithContext(ctx)

	eg.Go(func() error {
		if err := r.db.QueryRow(egCtx, countQuery, filterArgs...).Scan(&total); err != nil {
			return fmt.Errorf("count cases: %w", err)
		}
		return nil
	})

	eg.Go(func() error {
		rows, err := r.db.Query(egCtx, dataQuery, dataArgs...)
		if err != nil {
			return fmt.Errorf("query cases: %w", err)
		}
		defer rows.Close()

		result := make([]domain.SearchCaseView, 0, req.Pagination.Limit)
		for rows.Next() {
			var cv domain.SearchCaseView
			var caseType, subject, description string
			var severity, issueType, engagementType, workState *string
			var createdAt, updatedAt time.Time
			var aeID, aeName *string
			var pcID, pcNumber *string
			var rcID, rcNumber *string
			var prodID, prodName string
			var depID, depName string
			var dpID, dpName string
			var creatorEmail string
			if err := rows.Scan(
				&cv.ID, &cv.Number, &cv.InternalID,
				&caseType, &subject, &description, &severity, &issueType, &cv.State,
				&engagementType, &workState, &createdAt, &updatedAt,
				&creatorEmail,
				&cv.Project.ID, &cv.Project.Name,
				&depID, &depName,
				&dpID, &dpName,
				&prodID, &prodName,
				&aeID, &aeName,
				&pcID, &pcNumber,
				&rcID, &rcNumber,
			); err != nil {
				return fmt.Errorf("scan case: %w", err)
			}
			cv.Deployment = &domain.EntityRef{ID: depID, Name: depName}
			cv.DeployedProduct = &domain.EntityRef{ID: dpID, Name: dpName}
			cv.Type = caseType
			cv.Subject = &subject
			cv.Description = &description
			cv.Severity = severity
			cv.IssueType = issueType
			cv.EngagementType = engagementType
			cv.WorkState = workState
			cv.CreatedOn = createdAt.UTC().Format(time.RFC3339)
			cv.UpdatedOn = updatedAt.UTC().Format(time.RFC3339)
			cv.Product = &domain.EntityRef{ID: prodID, Name: prodName}
			// The search projection carries only the creator's email, no id or
			// display name, so the canonical reference keeps a null id.
			cv.CreatedBy = domain.NewUserReference("", creatorEmail, "")
			if aeID != nil {
				cv.AssignedEngineer = domain.NewUserReference(*aeID, "", *aeName)
			}
			if pcID != nil {
				cv.ParentCase = &domain.EntityRef{ID: *pcID, Name: *pcNumber}
			}
			if rcID != nil {
				cv.RelatedCase = &domain.EntityRef{ID: *rcID, Name: *rcNumber}
			}
			result = append(result, cv)
		}
		if err := rows.Err(); err != nil {
			return fmt.Errorf("iterate cases: %w", err)
		}
		cases = result
		return nil
	})

	if err := eg.Wait(); err != nil {
		return nil, 0, err
	}

	return cases, total, nil
}
