-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- onboarding_step.event_type was sized for entity-service's own Salesforce
-- operations (CREATED, UPDATED, RESTORED, PORTAL_WRITE). csm-notification-service
-- records the IDENTITY and EMAIL steps with the event it handled,
-- "project_contact.invited" (23 characters), so every one of its writes failed
-- with SQLSTATE 22001. 64 leaves room for dotted event names of that shape.
ALTER TABLE onboarding_step ALTER COLUMN event_type TYPE VARCHAR(64);
