-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- publish_claimed_on: an internal concurrency-control marker, never exposed
-- on the API -- set atomically by AutoPublish (ClaimForAutoPublish) before it
-- starts creating cases, and cleared when that attempt finishes (success or
-- failure). Its only purpose is to stop two AutoPublish attempts for the
-- same row from fanning out to the same projects at once (an overlapping
-- scheduled-task tick); a claim older than the service's own staleness
-- window is treated as abandoned and can be reclaimed, the same "stale
-- claim" reasoning scheduled_task_run's own claim/retry design already
-- uses. It does not, and cannot, prevent a race against a manual Publish
-- click (which has no notion of this column at all) -- see
-- AnnouncementRequestService.AutoPublish's own doc comment.
ALTER TABLE announcement_requests ADD COLUMN publish_claimed_on TIMESTAMPTZ;
