-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- Narrowing back fails if any row holds a value longer than 20 characters,
-- which is every row csm-notification-service wrote after the up migration.
-- That failure is deliberate: truncating would silently corrupt the ledger.
-- Delete or shorten those rows first if a rollback is really needed.
ALTER TABLE onboarding_step ALTER COLUMN event_type TYPE VARCHAR(20);
