-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- Kept in its own transaction: ALTER TYPE ... ADD VALUE can't run in the same
-- transaction as a statement that uses the new value. "Rejected - Visa
-- Issues" no longer appears in ServiceNow's live choice list (retired/folded
-- at some point) but still shows up as a raw value on older allocation
-- records, and is distinct enough from REJECTED_OTHER to keep separately
-- queryable.
ALTER TYPE engagement_allocation_state_enum ADD VALUE IF NOT EXISTS 'REJECTED_VISA_ISSUES';
